#!/bin/bash

#
# This script updates the aqua config (aqua.yaml | .aqua.yaml) in the current directory.
# It updates the version of the standard registry and then update the packages in the config
# to their latest versions.
#
# You won't need to run `aqua i` again after that, because aqua supports lazy install:
# https://aquaproj.github.io/docs/tutorial-basics/lazy-install/
#

if ! which aqua &>/dev/null; then
  echo "aqua command not found."
  exit 1
fi
if ! which yq &>/dev/null; then
  echo "yq command is required to run."
  exit 1
fi

aqua_config=aqua.yaml
if [ ! -e $aqua_config ]; then
  aqua_config=.aqua.yaml
  if [ ! -e $aqua_config ]; then
    echo "aqua.yaml and .aqua.yaml not found."
    exit 1
  fi
fi
echo "Updating $aqua_config"

temp=$(mktemp aqua-XXXXX --suffix=.yaml --dry-run)
echo "Using temp config: $temp"
aqua init "$temp"

# merge registries other than standard
# shellcheck disable=SC2016
yq '.registries[] | select(.type != "standard") | {"registries": [.]}' $aqua_config | yq eval-all '. as $item ireduce ({}; . *+ $item)' "$temp" - > "merged-$temp"
mv "merged-$temp" "$temp"

yq '.packages[] | ((.registry // "standard") + "," + .name)' $aqua_config | cut -d@ -f1 | xargs aqua -c "$temp" g -i -f -

mv "$temp" $aqua_config

aqua i -l
