#!/usr/bin/env ruby

if ARGV.length < 2
  puts "need two arguments."
  exit
end

target_dir = ARGV[0]
pattern = ARGV[1].gsub(".", "/")

jars = `find #{target_dir} -name '*.jar' -type f`
jars.split.each { |jar|
  result = `jar tf #{jar} | grep #{pattern}`
  if !result.empty?
    puts "Found #{result} in #{jar}"
  end
}
