#!/usr/bin/env ruby

if ARGV.length < 2
  puts <<-EOS
  Usage:
  > #{File.basename(__FILE__)} <directory> <pattern>
  EOS
  exit
end

target_dir = ARGV[0]
pattern = ARGV[1].gsub(".", "/")

jars = `find #{target_dir} -name '*.jar' -type f`
jars.split.each { |jar|
  result = `jar tf #{jar} | grep #{pattern}`
  if !result.empty?
    puts "#{jar}:"
    result.lines { |line| puts "  #{line}" }
  end
}
