#!/bin/bash

color=$(tput setaf $(( RANDOM % 6 + 1 )) && tput bold)
end=$(tput sgr0)

echo ${color}===========================================================================${end}
echo ${color}===== git checkout master${end}
git checkout master

echo
echo ${color}===========================================================================${end}
echo ${color}===== git pull upstream master${end}
git pull upstream master

echo
echo ${color}===========================================================================${end}
echo ${color}===== git push origin master${end}
origin=$(git remote | grep origin)
if [ "$origin" == "" ]; then
  echo No origin remote repository
  exit 0
fi
git push origin master
