#!/bin/sh

if [ "x$1" = "x" ]; then
  echo 'grep -nEe "WARN|ERROR|Caused by" -e "^[._[:alnum:]]+(Exception|Error)"'
else
  grep --color=auto -nEe "WARN|ERROR|Caused by" -e "^[._[:alnum:]]+(Exception|Error)" $*
fi
