#!/bin/sh

if [ "$1" = "" ]; then
  echo 'grep -Ee "WARN|ERROR|Caused by" -e "^[._[:alnum:]]+(Exception|Error)"'
else
  grep --color=auto $2 -Ee "WARN|ERROR|Caused by" -e "^[._[:alnum:]]+(Exception|Error)" "$@"
fi
