#!/usr/bin/env bash

set -o noclobber

red=`tput setaf 1`
end=`tput sgr0`

usage() {
  cat <<EOT
Usage:
  $(basename $0) <source> <target>
EOT
}

if [ -z $2 ]; then
  usage
  exit
fi

dryrun=

while getopts hd OPT; do
  case $OPT in
    h)
      usage
      exit
      ;;
    d)
      dryrun=true
      ;;
  esac
done
shift $((OPTIND - 1))

source=$1
target=$2

if [ ! -d $source ]; then
  echo ${red}"🔥 Directory does not exist. > $source"${end} 1>&2
  exit 1
else
  source=$(dirname $source)/$(basename $source)
fi
if [ ! -d $target ]; then
  echo ${red}"🔥 Diretory does not exist. > $target"${end} 1>&2
  exit 1
else
  target=$(dirname $target)/$(basename $target)
fi

echo "Merging $source/ -> $target/..."

# moving
for d in $source/*; do
  if [ ! -d $d ]; then
    continue
  fi
  if [ "$dryrun" == "true" ]; then
    echo mv -nv $d $target/
  else
    mv -nv $d $target/
  fi
done

# merging
if [ "$dryrun" != "true" ]; then
  for d in $source/*; do
    if [ ! -d $d ]; then
      continue
    fi
    mv -nv $d/* $target/$(basename $d)/
  done
fi
