#!/bin/sh

if [ -e $1 ]; then
  echo "Usage: > monitor-connections <port>"
  exit 1
fi

while true
do
  echo -----------------------------------------------------------------------------------
  netstat -a | grep "$1"
  netstat -a | grep "$1" -c
  sleep 5
done

