#!/bin/sh

#dirs=`git clean -dxn | cut -d' ' -f3 | sort | uniq`
dirs=`find . -name target -type d | xargs dirname | sort | uniq`
for dir in $dirs; do
  wc=`ls $dir | grep -E "pom.xml|src" | wc -l`
  if [ $wc -eq 0 ]; then
    echo Clean $dir
    rm -r $dir
  fi
done
