#!/bin/sh

label=${1:-camel}

version=2.2.0.fuse-720018-redhat-00001
catalog=https://maven.repository.redhat.com/ga/io/fabric8/archetypes/archetypes-catalog/$version/archetypes-catalog-$version-archetype-catalog.xml

command=mvn org.apache.maven.plugins:maven-archetype-plugin:2.4:generate \
  -DarchetypeCatalog=$catalog \
  -DarchetypeGroupId=org.jboss.fuse.fis.archetypes \
  -DarchetypeArtifactId=spring-boot-${label}-archetype \
  -DarchetypeVersion=$version

echo $command
$command
