#!/bin/sh

if [ -z $1 ]; then
    echo "Usage:"
    echo "  `basename $0` <settings> [label]"
    exit
fi

settings=$1
label=${2:-camel}

version=2.2.0.fuse-720018-redhat-00001
catalog=https://maven.repository.redhat.com/ga/io/fabric8/archetypes/archetypes-catalog/$version/archetypes-catalog-$version-archetype-catalog.xml

cmd="mvn -s $settings org.apache.maven.plugins:maven-archetype-plugin:2.4:generate \
  -DarchetypeCatalog=$catalog \
  -DarchetypeGroupId=org.jboss.fuse.fis.archetypes \
  -DarchetypeArtifactId=spring-boot-${label}-archetype \
  -DarchetypeVersion=$version"

echo $cmd
$cmd
