#!/bin/sh

USE_EXISTING_CONFIG="--use-existing-config"
while getopts i OPT
do
  case $OPT in
    "i") USE_EXISTING_CONFIG="";;
  esac
done

PUBLIC_HOSTNAME=127.0.0.1
HOST_DATA_DIR=$HOME/work/openshift/data
echo "oc cluster up --public-hostname=$PUBLIC_HOSTNAME $USE_EXISTING_CONFIG --host-data-dir=$HOST_DATA_DIR"
oc cluster up --public-hostname=$PUBLIC_HOSTNAME $USE_EXISTING_CONFIG --host-data-dir=$HOST_DATA_DIR
