#!/bin/sh

color=`tput setaf 1 && tput bold`
end=`tput sgr0`

if [ -z $1 ]; then
  echo "Usage: `basename $0` <pod name>"
  exit 1
fi

pods="$(oc get pods -o name | grep $1)"

if [ "$pods" == "" ]; then
  echo ${color}Pod name \"$1\" not found${end}
  exit 0
fi

n=`echo "$pods" | wc -l`
if [ $n -eq 1 ]; then
  echo $pods | xargs oc describe
else
  echo ${color}Pod name \"$1\" is ambiguous:${end}
  echo "$pods"
fi
