#!/bin/sh

color=`tput setaf 1 && tput bold`
end=`tput sgr0`

if [ -z $1 ]; then
  echo "Usage: `basename $0` <pod name>"
  exit 1
fi

pods="$(oc get pods -o name | grep $1)"

if [ "$pods" == "" ]; then
  echo ${color}Pod name \"$1\" not found${end}
  exit 0
fi

echo "$pods"
read -p "Delete these pods? [y/N]: " yn

if [ "$yn" == "y" ]; then
  echo $pods | xargs oc delete
fi
