#!/bin/sh

if [ -z $2 ]; then
  echo "Usage: `basename $0` <user@host> <password>"
  exit 1
fi

user_host=$1
pass=$2
guid=`echo $user_host | cut -d@ -f2 | cut -d. -f2`
sshpass -p "$pass" ssh -t $user_host "sudo tail /home/ec2-user/cluster-$guid/.openshift_install.log"
