#!/usr/bin/env ruby

def usage
  puts "Usage: #{File.basename(__FILE__)} [-git] <target project>"
end

if ARGV.length < 1
  usage
  exit 1
end

target_arg = ARGV.select { |arg| arg !~ /^-.*$/ }
if target_arg.empty?
  usage
  exit 1
end
target = target_arg[0].chomp("/")

zip = target + ".zip"
if File.exists?(zip)
  puts "deleting existing #{zip}"
  File.delete(zip)
end

docs = [ "README.md" ]
poms = [ "pom.xml" ] + `find #{target} -name pom.xml -type f`.split
gradles = [ "settings.gradle" ] + `find #{target} -name *.gradle -type f`.split
soapuis = `find #{target} -name soapui-project.xml -type f`.split
srcs = `find #{target} -name src -type d`.split

# files
(docs + poms + gradles + soapuis).each { |entry|
  `zip #{zip} #{entry}` if entry !~ /\/bin\/|\/build\/|\/target\/|\/\..+\//
}
# dirs
srcs.each { |entry|
  `zip #{zip} -r #{entry}` if entry !~ /\/bin\/|\/build\/|\/target\/|\/\..+\//
}

if ARGV.include? "-git"
  `zip #{zip} -r .git`
  `zip #{zip} .gitignore`
end
