#!/bin/bash

if [ -z $2 ]; then
    echo "Usage:"
    echo "  $(basename $0) <target> <replace>"
    exit 1
fi

echo -e "\e[32m> ag \"$1\" -l | xargs sed -i \"s/$1/$2/g\"\e[m"
ag "$1" -l | xargs sed -i "s/$1/$2/g"
