#!/bin/sh

LSREGISTER=/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister
$LSREGISTER -kill -seed -r -f -v -domain local -domain user -domain system
