#!/usr/bin/env ruby

if ARGV.length == 0
  puts "no argument."
  exit
end

file = ARGV[0]
if !File.exists?(file + ".md5")
  puts "no md5 file."
  exit
end

os = `uname`
if os.start_with? "Linux"
  md5 = "md5sum"
else
  md5 = "md5"
end

puts "calculating md5 sum: #{file}"
md5 = `#{md5} #{file}`
puts "actual:   #{md5}"
if os.start_with? "Linux"
  md5 = md5.split[0]
else
  md5 = md5.split[3]
end
expected = `cat #{file}.md5`
puts "expected: #{expected}"
if expected.include? md5
  puts "ok."
else
  puts "broken."
end
