#!/usr/bin/env ruby

if ARGV.length == 0
  puts "no argument."
  exit
end

file = ARGV[0]
if File.exists?(file + ".md5")
  ext = "md5"
elsif File.exists?(file + ".MD5")
  ext = "MD5"
else
  puts "no md5 file."
  exit
end

linux = RbConfig::CONFIG['host_os'] =~ /linux/
if linux
  md5 = "md5sum"
else
  md5 = "md5"
end

puts "calculating md5 sum: #{file}"
checksum = `#{md5} "#{file}"`
puts "actual:   #{checksum}"
checksum = linux ? checksum.split[0] : checksum.split[3]

expected = `cat "#{file}.#{ext}"`
puts "expected: #{expected}"
puts expected.downcase.include?(checksum) ? "ok." : "broken."
